-- Bulk Seed Students for Washington School LRC
-- Total Students: 77
-- Sequential IDs: WSI-LRC-S-0001 to WSI-LRC-S-0077

INSERT INTO "Students" (library_id, full_name, grade_level) VALUES
  ('WSI-LRC-S-0001', 'Ariannelle B. Arguelles', 'Grade 1'),
  ('WSI-LRC-S-0002', 'Joelle Mae A. Micua', 'Grade 1'),
  ('WSI-LRC-S-0003', 'Princess Shonna H. Mostera', 'Grade 1'),
  ('WSI-LRC-S-0004', 'Jamela Emmanuelle B. Parel', 'Grade 1'),
  ('WSI-LRC-S-0005', 'Luna Gaile S. Punla', 'Grade 1'),
  ('WSI-LRC-S-0006', 'Avery Jade T. Ragos', 'Grade 1'),
  ('WSI-LRC-S-0007', 'Vince Gideon R. Cardinal', 'Grade 1'),
  ('WSI-LRC-S-0008', 'Zion Anthony C. Dela Cruz', 'Grade 1'),
  ('WSI-LRC-S-0009', 'Austin Kale A. Labesig', 'Grade 1'),
  ('WSI-LRC-S-0010', 'Jon Andrew B. Limjuico', 'Grade 1'),
  ('WSI-LRC-S-0011', 'Deaon Ayval B. Machado', 'Grade 1'),
  ('WSI-LRC-S-0012', 'Manuela Imelda Barquin', 'Grade 2'),
  ('WSI-LRC-S-0013', 'Ma. Princess Kate N. Eburlas', 'Grade 2'),
  ('WSI-LRC-S-0014', 'Bianca Charlize Isabelle O. Moreno', 'Grade 2'),
  ('WSI-LRC-S-0015', 'Adriel Kyrie S. Arciga', 'Grade 2'),
  ('WSI-LRC-S-0016', 'Clark Nathan S. Del Villar', 'Grade 2'),
  ('WSI-LRC-S-0017', 'Klay Arden C. Eliseo', 'Grade 2'),
  ('WSI-LRC-S-0018', 'Jon Ezekiel Iglesias', 'Grade 2'),
  ('WSI-LRC-S-0019', 'Owen Bryce V. Sanchez', 'Grade 2'),
  ('WSI-LRC-S-0020', 'Aliyah B. Arguelles', 'Grade 4'),
  ('WSI-LRC-S-0021', 'Aquila Coleen A. Dela Cruz', 'Grade 4'),
  ('WSI-LRC-S-0022', 'Mia Xerena R. Maulanin', 'Grade 4'),
  ('WSI-LRC-S-0023', 'Psalm Adriel P. Bugarin', 'Grade 4'),
  ('WSI-LRC-S-0024', 'Jaiden Gabriel D. White', 'Grade 4'),
  ('WSI-LRC-S-0025', 'Noah Rei Q. Vergara', 'Grade 4'),
  ('WSI-LRC-S-0026', 'Adam Railey M. Robles', 'Grade 4'),
  ('WSI-LRC-S-0027', 'Hans Keefer N. Eburlas', 'Grade 4'),
  ('WSI-LRC-S-0028', 'Cris Savannah P. Bugarin', 'Grade 5'),
  ('WSI-LRC-S-0029', 'Elaijah Camille R. Aralar', 'Grade 5'),
  ('WSI-LRC-S-0030', 'Liam Jon E. Miranda', 'Grade 5'),
  ('WSI-LRC-S-0031', 'Sean Adriel C. Langga', 'Grade 5'),
  ('WSI-LRC-S-0032', 'Kean Paulo N. Eburlas', 'Grade 5'),
  ('WSI-LRC-S-0033', 'Samuel Isaac F. Cabigon', 'Grade 5'),
  ('WSI-LRC-S-0034', 'Alphonse Caius A. Palisoc', 'Grade 5'),
  ('WSI-LRC-S-0035', 'Aziel Klay A. Labesig', 'Grade 5'),
  ('WSI-LRC-S-0036', 'Kim Shaun', 'Grade 5'),
  ('WSI-LRC-S-0037', 'Leian Savrine S. Manalo', 'Grade 6'),
  ('WSI-LRC-S-0038', 'Rylan Korbin Q. Givera', 'Grade 6'),
  ('WSI-LRC-S-0039', 'Zoe Emmanuel Torino A. Grospe', 'Grade 6'),
  ('WSI-LRC-S-0040', 'Ande Sebastian A. Lalo', 'Grade 6'),
  ('WSI-LRC-S-0041', 'JM Kurt A. Micua', 'Grade 6'),
  ('WSI-LRC-S-0042', 'Dylan Kiefer C. Talampas', 'Grade 6'),
  ('WSI-LRC-S-0043', 'Yuna G. Jeon', 'Grade 7'),
  ('WSI-LRC-S-0044', 'Sabriella P. Ladiana', 'Grade 7'),
  ('WSI-LRC-S-0045', 'Alia Lejame G. Regacho', 'Grade 7'),
  ('WSI-LRC-S-0046', 'Kaas G. Gamuyao', 'Grade 7'),
  ('WSI-LRC-S-0047', 'Preihgrie Rose L. Cortez', 'Grade 8'),
  ('WSI-LRC-S-0048', 'Fabienne Faith T. De Castro', 'Grade 8'),
  ('WSI-LRC-S-0049', 'Zye G. Gamuyao', 'Grade 8'),
  ('WSI-LRC-S-0050', 'Nathalia M. Quevido', 'Grade 8'),
  ('WSI-LRC-S-0051', 'Paulajoy B. Sales', 'Grade 8'),
  ('WSI-LRC-S-0052', 'Shannel M. Santos', 'Grade 8'),
  ('WSI-LRC-S-0053', 'Summer Ahshiey D. Tenedero', 'Grade 8'),
  ('WSI-LRC-S-0054', 'Victoria Maris I. Valencerina', 'Grade 8'),
  ('WSI-LRC-S-0055', 'Caleb Jedaiah C. Estilo', 'Grade 8'),
  ('WSI-LRC-S-0056', 'Diesel Rapha Camaro A. Grospe', 'Grade 8'),
  ('WSI-LRC-S-0057', 'Shawn Jacob C. Langga', 'Grade 8'),
  ('WSI-LRC-S-0058', 'Drexel V. Marquez', 'Grade 8'),
  ('WSI-LRC-S-0059', 'Lewis Bran E. Miranda', 'Grade 8'),
  ('WSI-LRC-S-0060', 'John Bronfield S. Montifar', 'Grade 8'),
  ('WSI-LRC-S-0061', 'Yves Lucius E. Salao', 'Grade 8'),
  ('WSI-LRC-S-0062', 'Nathan Rei Q. Vergara', 'Grade 8'),
  ('WSI-LRC-S-0063', 'Shamcey P. Silva', 'Grade 9'),
  ('WSI-LRC-S-0064', 'Princess Janelle D. Wagan', 'Grade 9'),
  ('WSI-LRC-S-0065', 'Nigel P. Ladiana', 'Grade 9'),
  ('WSI-LRC-S-0066', 'Aaron Jude T. Ragos', 'Grade 9'),
  ('WSI-LRC-S-0067', 'Jillian Nicole D. Ergina', 'Grade 10'),
  ('WSI-LRC-S-0068', 'Leona Steffany S. Manalo', 'Grade 10'),
  ('WSI-LRC-S-0069', 'Vincent Jr. R. Cardinal', 'Grade 10'),
  ('WSI-LRC-S-0070', 'Sean Ryleigh C. Gonzales', 'Grade 10'),
  ('WSI-LRC-S-0071', 'Gaibrielle Maryneah L. Boncan', 'Grade 11'),
  ('WSI-LRC-S-0072', 'Fuelle Jireh Cayenne A. Grospe', 'Grade 11'),
  ('WSI-LRC-S-0073', 'Ezekiel Joel F. Cabigon', 'Grade 11'),
  ('WSI-LRC-S-0074', 'Majja V. Bautista', 'Grade 12'),
  ('WSI-LRC-S-0075', 'Shaniah Reigne Villar', 'Grade 12'),
  ('WSI-LRC-S-0076', 'Yeshaya Uzziel E. Manio', 'Grade 12'),
  ('WSI-LRC-S-0077', 'Park Yeon Woo', 'Grade 12');
